title: Ourbot Beta 설명페이지
author: OurbotAdmin
subtitle: Welcome to ourbot page

url: "https://cloudpbxa.github.io/"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/cloudPBXa/cloudPBXa.github.io"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://github.com/cloudPBXa/cloudPBXa.github.io"
